### ISSUE TITLE
Genesis games not being picked up

### ISSUE THREAD

**Issue by norwichred** [ResetCollection/support#101]
Hi!

Great front end, but it won’t recognise mega drive / genesis games in .bin format.

All my roms are in this format :(

**Comment by ReCoJav** [comment]
@norwichred I am really sorry! .bin isn't a default extension in the extensions that RESET looks for. The good news is that you can updated what extensions RESET looks for every system that you scan for.

![image](https://user-images.githubusercontent.com/56896660/82521946-d5e10d00-9adc-11ea-81c5-0a6ae0bd1c94.png)

When you add a system or are adding games, when you reach the screen above, click on "Add ROMs with these extensions" and you will then be able to edit that list.. add "bin" to that list. It's comma separated, so please make sure to add a comma before it.. like "zip,7z,md,gen,smd,bin"

Let me know if that works for you!

Take care,
-Jav

**Comment by norwichred** [comment]
You are a star thank you!  And your front end is awesome!  Cheers for the help!

**Comment by ReCoJav** [comment]
Glad that worked!!
