### ISSUE TITLE
Native Android games support

### ISSUE THREAD

**Issue by ShaynAshaen** [ResetCollection/support#109]
The ability to view and launch native Android games from the app. 

Choosing which apps/games appear is also favorable because some games maybe considered regular apps by Android system.

**Comment by ReCoJav** [comment]
Hey there! Thanks for creating this request!

I'm actually working on this right now, putting some finishing touches on it and then need to test it out on all of my devices to make sure it looks good on different screen sizes.

Here's a little demo of what it'll look like:
https://drive.google.com/file/d/1uIvOMnMSFKZfxM9AP1zpZj0sMh2jLwId/view?usp=sharing

**Comment by ReCoJav** [comment]
@ShaynAshaen  closing issue... Android native games is available as a system now 👍
