### ISSUE TITLE
Add Native Android games system collection

### ISSUE THREAD

**Issue by ReCoJav** [ResetCollection/support#5]
### Overview
Gotta love gaming on Android, and why shouldn't we be able to see the games that we have on our device in RESET Collection? Let's add "Android" as a system that you can add to the RESET Collection.

### Acceptance Criteria
* User can add an Android collection
* App scans the device for games that are installed and adds them to the collection
* Clicking on an Android game will launch that game app

**Comment by Magen78** [comment]
This is the best suggestion for me!  With this idea we could have more space in the telephone main screen , cause with just one icon we have all our games integrated ! Like arc browser app,  but reset app is easier to use and the best and better for me!

**Comment by ReCoJav** [comment]
@Magen78 
If you haven't updated RESET yet, this feature is now available!

Thanks!

**Comment by Magen78** [comment]
Thanks a lot for your post! I have updated the app Yesterday and is really Amazing! You did it! And works perfect! Now i have all My games in one app! Thanks again for your great work... (Remember if is possible in a next update to include the Sega game Gear Nostalgia emulador) best regards
