### ISSUE TITLE
Adding roms gives error

### ISSUE THREAD

**Issue by DJCorndawg** [ResetCollection/support#6]
Get this error when trying to add any roms.
![Screenshot_20191030-145322_Reset Collection](https://user-images.githubusercontent.com/4247701/67893925-8f6a9780-fb25-11e9-8cc1-70938739b406.jpg)

**Comment by ReCoJav** [comment]
Oh no!

I did notice something, you seem to have an old version of the app. I'm not sure if this issue also exists in the newest version. I'm trying to fix why some people have the old version... 

Would you mind uninstalling the app, and installing it again using this link: https://play.google.com/apps/internaltest/4699424686957624380

Also, can read here and if you need to respond, can do it in the comments:

https://www.reddit.com/r/EmulationOnAndroid/comments/dovz9r/i_created_an_android_emulation_front_end/f5u463j?utm_source=share&utm_medium=web2x

It explains some things. I'll get back to you later tonight when I research this... thanks!

**Comment by ReCoJav** [comment]
Fixed with latest version!
Release 0.101
Version code 4
