### ISSUE TITLE
Scraping dreamcast

### ISSUE THREAD

**Issue by Magen78** [ResetCollection/support#71]
![Screenshot_2020-04-19-05-36-27-621_com retroloungelab resetcollection](https://user-images.githubusercontent.com/63874233/79678866-2294a800-8200-11ea-818d-44802aec1bae.jpg)
Hi again!  Yesterday i added and scraped the dreamcast (redream)  system.  The app has created correctly the game art boxes,  but some empty art boxes have been created too with the words track3, track1… etc… i have tried to erase them with remove game from database option but with no succes.i remenber that i saw the same problem with arc browser app and the solution i found was a hide option when you do a long press in the art box… Thanks Javier!

**Comment by ReCoJav** [comment]
Doh, sorry this is happening!

So if you go to like "track01" above, and select "Remove game from database", it doesn't actually get removed?

Also, can you tell me what the filename of that "track01" item above is? When you bring up the game menu, you'll see the file path and file name at the top of the game menu. Please let me know what the file name is.

Thank you!

**Comment by Magen78** [comment]
Sorry Javier! Was my fault, now I can remove them without remove game option... Thanks again
