### ISSUE TITLE
Editing already added systems

### ISSUE THREAD

**Issue by lamvuong2019** [ResetCollection/support#81]
Not often but can happen, you wanted to change a system emulator or directory, there is no option to change this at the moment.

**Comment by Dion-Guy** [comment]
Unless I'm misunderstanding your request, this is possible - I just changed the Commodore 64 system from using C64.emu to Retroarch (Vice).

Long press on the icon of your system and a menu will appear - choose "Set emulator for all games" and you can pick a new one.  If you want to pick a new directory for your games then choose "Fix ROM directory".

**Comment by lamvuong2019** [comment]
I think I over looked, thanks for pointing this out.
