### ISSUE TITLE
Please add LHA extension for scanning Amiga games (RetroArch: P-UAE)

### ISSUE THREAD

**Issue by Dion-Guy** [ResetCollection/support#82]
RetroArch (P-UAE) can load Amiga WHDLoad games directly from LHA files.  However, Reset Collection does not recognise this as a valid extension, so ignores them when scanning the game directory.

Please add LHA as a recognised extension - many thanks!

**Comment by ReCoJav** [comment]
Hello @Dion-Guy !!

Sorry this isn't a default extension! But just FYI, you can edit the extensions RESET will use when scanning for files.

When you get to the "Choose scrape and scan options" screen, click on "Add ROMs with these extensions" and add (or even delete) any extension. Make sure to separate extensions by comma.

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/56896660/81139525-e4df9100-8f1a-11ea-8935-5dfb3dfdeede.png">

Let me know if this works for you.

Thanks and take care!!
-Jav

**Comment by Dion-Guy** [comment]
My bad!  That worked perfectly, and it was my fault for not knowing that the extensions were editable (which is a great feature).

It might be an idea to still add LHA as a default extension, but this is not a bug so I am closing this issue.  Many thanks for your very fast reply - your support is excellent.
