### ISSUE TITLE
Box art changes not sticking when exiting and reloading app

### ISSUE THREAD

**Issue by Dion-Guy** [ResetCollection/support#83]
I've found a problem with changing box art.  Sometimes when you add a system and scrape some games, and then change the box art, it doesn't stick after exiting and reverts to the old box art when you reload the app.

I've had this with both the Amiga and C64 systems, although I managed to fix it on the Amiga by changing one box art to a custom image (not a scraped one) and then for some reason any further changes I made stuck (for that system).

But no matter what I do with the C64 box art any changes I make do not stick when exiting and reloading the app.  I've tried a custom image, changing to "no box art", deleting all the images from the Reset Collection folder in Pictures, deleting and re-adding the collection, and even uninstalling and reinstalling the app!

I made a little video to demonstrate this issue (private, so not all YouTube can see!):
https://youtu.be/SD2lfmUV2wI

**Comment by ReCoJav** [comment]
ack, dang... ok, bummed to see that. Sorry it's happening! I'll make sure to take a look. Thanks for bringing this to my attention and the video!

**Comment by ReCoJav** [comment]
Oh man, this is so weird... I've only been able to reproduce this with Commodore 64 games! Other systems work fine.

Well, now to figure out why this is happening!

**Comment by ReCoJav** [comment]
Hey @Dion-Guy , I think I found a temporary workaround for you...

So after you make any changes to the box art (or any other art), instead of closing out the app by pushing back button and selecting "exit", double click the home button to bring up all of the open apps, and push down on RESET to completely kill it.

The next time you open RESET, everything should be saved.

I'm working on a fix so that this issue doesn't happen when exiting by pushing back. but for now, let me know if that workaround works for you.

thanks!
-Jav

**Comment by Dion-Guy** [comment]
> Oh man, this is so weird... I've only been able to reproduce this with Commodore 64 games! Other systems work fine.

Just wanted to share another video where this is happening with the Amiga system.  It happened to me before (as mentioned in my first post) but it happened again as soon as I did "Scan game folder for new games":

https://youtu.be/DzdBuZ4MZpo

I'm only posting this to show you that (a) it's not exclusive to the Commodore 64, and (b) it can happen after scanning for new games, not just adding a system.

On a more positive note - many thanks for the workaround, which works a treat.  It worked for both the Commodore 64 games and the newly added Amiga games.

Thanks again for your fast attention to this issue.  I think Reset Collection is a great front end and your excellent support is the cherry on the cake!
